import { RalphLoopContext } from '../../types';

export function generateRalphLoop(ctx: RalphLoopContext): string {
  return `#!/bin/bash
# Ralph loop for phase: ${ctx.phaseName}
# Thin wrapper — story picking, snapshots, verifier quorum, model escalation,
# and commits all live in the sugar CLI's \`sugar run\` (src/lib/loop-runner.ts).
# This script exists only so existing invocations (./ralph-loop.sh N model)
# keep working.
# Usage: ./ralph-loop.sh [max_iterations] [default_model]
# Generated by Sugar — do not edit manually
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
MAX_ITERATIONS="\${1:-${ctx.maxIterations}}"
DEFAULT_MODEL="\${2:-${ctx.defaultModel}}"

exec ${ctx.sugarBin} run "$SCRIPT_DIR" --max-iterations "$MAX_ITERATIONS" --model "$DEFAULT_MODEL"
`;
}