import { RalphLoopContext } from '../../types';

export function generateRalphLoop(ctx: RalphLoopContext): string {
  return `#!/bin/bash
# Ralph loop for phase: ${ctx.phaseName}
# Usage: ./ralph-loop.sh [max_iterations] [default_model]
# Generated by Sugar — do not edit manually
set -e

MAX_ITERATIONS=\${1:-${ctx.maxIterations}}
DEFAULT_MODEL="\${2:-${ctx.defaultModel}}"
ESCALATION_MODEL="${ctx.escalationModel}"
CURRENT_MODEL="$DEFAULT_MODEL"
CONSECUTIVE_FAILURES=0
ESCALATION_THRESHOLD=${ctx.escalationThreshold}
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PRD_FILE="$SCRIPT_DIR/prd.json"
SUGAR="${ctx.sugarBin}"

echo "Starting Ralph loop — Phase: ${ctx.phaseName}"
echo "Max iterations: $MAX_ITERATIONS"
echo "Default model: $DEFAULT_MODEL | Escalation model: $ESCALATION_MODEL"

for i in $(seq 1 $MAX_ITERATIONS); do
  echo ""
  echo "========================================"
  echo "  Iteration $i of $MAX_ITERATIONS"
  echo "========================================"

  # Get next story and create snapshot
  STORY_ID=$($SUGAR pick-story --workspace "$SCRIPT_DIR" 2>/dev/null || echo "unknown")
  if [ "$STORY_ID" = "PHASE_COMPLETE" ]; then
    echo "All stories passed — phase complete!"
    exit 0
  fi

  $SUGAR snapshot --workspace "$SCRIPT_DIR" --story "$STORY_ID" --attempt "$i" 2>/dev/null || true

  # Run implementer agent
  OUTPUT=$(claude --model "$CURRENT_MODEL" --dangerously-skip-permissions --print < "$SCRIPT_DIR/CLAUDE.md" 2>&1 | tee /dev/stderr) || true

  if echo "$OUTPUT" | grep -q "STORY_IMPLEMENTED"; then
    STORY_ID=$(echo "$OUTPUT" | grep -oE 'STORY_IMPLEMENTED:[A-Z]+-[0-9]+' | cut -d: -f2 | head -1)
    echo "Story $STORY_ID implemented — running verifier quorum..."

    # Run consensus verification via sugar CLI
    if $SUGAR verify --workspace "$SCRIPT_DIR" --story "$STORY_ID" --model "$CURRENT_MODEL"; then
      echo "Consensus: PASS — committing story $STORY_ID"
      git add -A && git commit -m "feat: $STORY_ID - verified by consensus"
      $SUGAR story-update --workspace "$SCRIPT_DIR" --story "$STORY_ID" --status passed
      CONSECUTIVE_FAILURES=0
      if [ "$CURRENT_MODEL" != "$DEFAULT_MODEL" ]; then
        echo ">>> De-escalating back to $DEFAULT_MODEL"
        CURRENT_MODEL="$DEFAULT_MODEL"
      fi
    else
      echo "Consensus: FAIL — rejecting story $STORY_ID"
      $SUGAR story-update --workspace "$SCRIPT_DIR" --story "$STORY_ID" --status rejected
      git checkout -- .
      CONSECUTIVE_FAILURES=$((CONSECUTIVE_FAILURES + 1))
    fi
  fi

  if echo "$OUTPUT" | grep -q "PHASE_COMPLETE"; then
    echo ""
    echo "Phase ${ctx.phaseName} complete at iteration $i!"
    exit 0
  fi

  # Model escalation check
  if echo "$OUTPUT" | grep -qiE "STORY_FAILED|stuck|blocked|retry.?exhausted"; then
    CONSECUTIVE_FAILURES=$((CONSECUTIVE_FAILURES + 1))
    echo "Failure detected ($CONSECUTIVE_FAILURES consecutive)"
    if [ "$CONSECUTIVE_FAILURES" -ge "$ESCALATION_THRESHOLD" ] && [ "$CURRENT_MODEL" != "$ESCALATION_MODEL" ]; then
      echo ">>> Escalating from $CURRENT_MODEL to $ESCALATION_MODEL"
      CURRENT_MODEL="$ESCALATION_MODEL"
    fi
  fi

  echo "[\$(date)] Iteration $i — model: $CURRENT_MODEL — result: $(echo "$OUTPUT" | grep -oE '(STORY_IMPLEMENTED|STORY_FAILED|PHASE_COMPLETE)' | head -1)" >> "$SCRIPT_DIR/progress.txt"
  echo "Iteration $i done. Continuing..."
  sleep 2
done

echo ""
echo "Reached max iterations ($MAX_ITERATIONS) without completing all stories."
echo "Check prd.json and progress.txt for status."
exit 1
`;
}
